### ISSUE TITLE
aws/aws-for-fluent-bit version in default values.yaml is very old, also sets IMDS v1 by default

### ISSUE THREAD

**Issue by divbell** [aws-observability/aws-otel-helm-charts#70]
I deployed this to our cluster but had IMDS errors and only partial logging and after reading many Github Issues threads, realized the chart ships a really old version and sets IMDS v1 by default.

Suggest modifying the default value for aws/aws-for-fluent-bit version in values.yaml to 2.28.1 from 2.21.1.  The v2.21.1 release is from Nov 2021 and there have been 18 releases since then, fixing a great number of issues and making improvements.

Additionally, setting imdsVersion to v2 by default (instead of v1) may lead to better outcomes.

This stuff is reasonably challenging to setup and validate, it's why people come for the chart, so keeping it up-to-date will help users be successful with it without a lot of labor tracking down defects that are already fixed in related packages.

**Comment by mhausenblas** [comment]
Hey @divbell, ADOT PM here and thanks for raising this issue. We're working on logs in OpenTelemetry upstream with the plan to support it in ADOT by mid 2023. Along with this work we will, going forward, remove support for Fluent Bit in this Helm chart. Due to this, we do not plan feature work on the [Fluent Bit template](https://github.com/aws-observability/aws-otel-helm-charts/tree/main/charts/adot-exporter-for-eks-on-ec2/templates/aws-for-fluent-bit), here.

**Comment by divbell** [comment]
That makes sense if fluent-bit is deprecated on your roadmap but bumping the version (or enabling IMDSv2) between now and then isn't much of a feature.

Basically if somebody deploys your release version today, it's not going to work well for them unless they specify a change to these default values.  Some may figure that out, others wlll just rip and replace with something else that works and won't be using this by mid-2023.  Something to think about anyway, thank you.

For posterity (in case anybody reads this stuck on it):

https://github.com/aws-observability/aws-otel-helm-charts/blob/main/charts/adot-exporter-for-eks-on-ec2/values.yaml#L25
change to v2

https://github.com/aws-observability/aws-otel-helm-charts/blob/main/charts/adot-exporter-for-eks-on-ec2/values.yaml#L28
change to 2.28.1 (or later)

**Comment by sayurin** [comment]
@divbell, aws/aws-for-fluent-bit version 2.21.1 (and 2.21.0) has a bug and it is fixed at [2.21.2](https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.21.2). So simply, change 2.21.1 to 2.21.2, adot fluentbit will work.

@mhausenblas, if can, please update aws for fluent bit version to 2.21.2 only.

And please update documentation.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-EKS-otel.html says:

> Amazon provides a Helm chart that you can use to set up the monitoring of Amazon Elastic Kubernetes Service on Amazon EC2. This monitoring uses the AWS Distro for OpenTelemetry(ADOT) Collector for metrics and Fluent Bit for logs. Therefore, the Helm chart is useful for customers who use Amazon EKS on Amazon EC2 and want to collect metrics and logs to send to CloudWatch Container Insights. For more information about this Helm chart, see [ADOT Helm chart for EKS on EC2 metrics and logs to Amazon CloudWatch Container Insights](https://github.com/aws-observability/aws-otel-helm-charts/tree/master/charts/adot-exporter-for-eks-on-ec2).

(... but this helm chart of adot is not working because of buggy version of aws for fluent bit.)
